[package]
name = "kada-hook"
version = "0.1.0"
edition = "2021"

[dependencies]
kada-core = { path = "../kada-core" }

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.13"

[target.'cfg(any(windows, target_os = "linux"))'.dependencies]
arboard = "3"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
